/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathInterface;

import java.util.ArrayList;
import java.util.Vector;
import org.apache.lucene.document.Document;

/**
 *
 * @author Lothar Soto Palma
 * @author Daniel López García
 * @author Iván Calle Gil
 * @author José Carlos Entrena Jiménez
 */
public class advancedPanel extends javax.swing.JPanel {

    /**
     * Creates new form advancedPanel
     */
    public advancedPanel() {
        initComponents();
    }
    
    public ArrayList<String> GetRange(){
        ArrayList<String> res=new ArrayList();
        res.add(range_bottom.getText());
        res.add(range_top.getText());
        return res;
    }
    public String GetField(){
        return jComboBox1.getSelectedItem().toString();
    }
    public String GetInfo(){
        String info;
        if(range_bottom.getText().equals("") && range_top.getText().equals("")){
            info="No hay rango";
        }else{
            StringBuilder sb =new StringBuilder();
            sb.append(GetField());
            sb.append("->");
            if(range_top.getText().equals("")){
                sb.append("mayor que ");
                sb.append(range_bottom.getText());
            }else if(range_bottom.getText().equals("")){
                sb.append("menor que ");
                sb.append(range_top.getText());
            }else{
                sb.append(range_bottom.getText());
                sb.append("-");
                sb.append(range_top.getText());
            }
            info=sb.toString();
            
        }
        return info;
    }
    public void Clear(){
        range_bottom.setText("");
        range_top.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        range_bottom = new javax.swing.JTextField();
        range_top = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        range_bottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                range_bottomActionPerformed(evt);
            }
        });

        jLabel5.setText("Busqueda por rango:");

        jLabel1.setText("Opciones avanzadas");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "Página inicio", "Página fin" }));
        jComboBox1.setSelectedItem(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(range_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(range_top, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, 0, 55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(range_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(range_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void range_bottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_range_bottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_range_bottomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField range_bottom;
    private javax.swing.JTextField range_top;
    // End of variables declaration//GEN-END:variables
}
