/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathInterface;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/**
 *
 * @author lot94
 */
public class filterPanel extends javax.swing.JPanel {

    /**
     * Creates new form filterpanel
     */
    public filterPanel() {
        initComponents();
        filterTextFields = new ArrayList();
        filterFields = new ArrayList();
        fieldTypeBox = new javax.swing.JComboBox();
    }

    public void setFieldsBox(javax.swing.JComboBox fields){
        fieldTypeBox = new javax.swing.JComboBox();
        for(int i = 0; i < fields.getItemCount(); i++){
            fieldTypeBox.addItem((String) fields.getItemAt(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filterRows = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Añadir Filtro:");

        jLabel2.setText("Búsqueda:");

        javax.swing.GroupLayout filterRowsLayout = new javax.swing.GroupLayout(filterRows);
        filterRows.setLayout(filterRowsLayout);
        filterRowsLayout.setHorizontalGroup(
            filterRowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterRowsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterRowsLayout.setVerticalGroup(
            filterRowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterRowsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterRows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JTextField newFilterTextField = new javax.swing.JTextField();
        javax.swing.JComboBox newFilterFields = new javax.swing.JComboBox();
        for(int i = 0; i < fieldTypeBox.getItemCount(); i++){
            newFilterFields.addItem((String) fieldTypeBox.getItemAt(i));
        }
        
        if(filterTextFields.size() < 4){
            filterTextFields.add(newFilterTextField);
            filterFields.add(newFilterFields);
        }
        
        updateFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateFrame() {
        int pos_Y = 25;
        for(int i = 0; i < filterTextFields.size(); i++){
            filterTextFields.get(i).setSize(200, 25);
            filterTextFields.get(i).setLocation(0, pos_Y);
            
            filterFields.get(i).setSize(100, 25);
            filterFields.get(i).setLocation(210, pos_Y);
            
            filterRows.add(filterFields.get(i));
            filterRows.add(filterTextFields.get(i));
            pos_Y += 25;
        }
        filterRows.validate();
        filterRows.repaint();
    }
    
    public ArrayList<javax.swing.JTextField> getFilterTextFields(){
        return filterTextFields;
    }
    
    public ArrayList<javax.swing.JComboBox> getFilterFields(){
        return filterFields;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filterRows;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private ArrayList<javax.swing.JTextField> filterTextFields;
    private ArrayList<javax.swing.JComboBox> filterFields;
    private javax.swing.JComboBox fieldTypeBox;
    
}
