/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathInterface;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.apache.lucene.document.Document;

/**
 *
 * @author lot94
 */
public class hitsTable extends javax.swing.JPanel {

    /**
     * Creates new form hitsTable
     */
    public hitsTable() {
        initComponents();
    }

    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        for(int i = 0; i < model.getRowCount(); i++)
            model.removeRow(i);
        model.setRowCount(0);
        Table.setModel(model);
        
    }
    
    public void updateTable(ArrayList<Document> hits){
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        
        String data[] = new String[2];
        for(int i = 0; i < hits.size(); i++){
            data[0] = String.valueOf(i+1);
            data[1] = hits.get(i).get("Titulo");
            model.addRow(data);
        }
        
        Table.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Título"
            }
        ));
        jScrollPane2.setViewportView(Table);

        jLabel1.setText("Hits para la búsqueda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
